[package]
name = "word-ladder"
version = "0.1.0"
authors = ["Thiago Nascimento <nascimenthiago@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-utils = "0.8.0"
cpu-time = "1.0.0"